AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

inherit_from: .rubocop_todo.yml
